$ErrorActionPreference = "Stop"

$PackageRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppRoot = Join-Path $PackageRoot "app"
$EnvPath = Join-Path $AppRoot ".env"

function Read-Required([string]$Label) {
    while ($true) {
        $rawValue = Read-Host $Label
        $value = $rawValue.Trim()
        if (-not [string]::IsNullOrWhiteSpace($value)) {
            return $value
        }
        Write-Host "Value is required. Please try again."
    }
}

function Read-WithDefault([string]$Label, [string]$DefaultValue) {
    $rawValue = Read-Host "$Label [$DefaultValue]"
    $value = $rawValue.Trim()
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $DefaultValue
    }
    return $value
}

if (-not (Test-Path $AppRoot)) {
    throw "Missing app directory: $AppRoot. Please run this script from the portable package root."
}

Write-Host "Waste paper ORC Feishu portable package setup"
Write-Host "Config file: $EnvPath"
Write-Host ""

if (Test-Path $EnvPath) {
    Write-Host "app\.env already exists."
    $rawOverwrite = Read-Host "Type YES to overwrite"
    $overwrite = $rawOverwrite.Trim()
    if ($overwrite -ne "YES") {
        Write-Host "Canceled. Existing config was not changed."
        exit 0
    }
}

$appId = Read-Required "Enter FEISHU_APP_ID"
$appSecret = Read-Required "Enter FEISHU_APP_SECRET"

Write-Host ""
Write-Host "Cloud OCR token is optional. Leave it empty to use local PP-OCRv5 mobile."
$cloudUrl = Read-WithDefault "PADDLEOCR_API_URL" "https://paddleocr.aistudio-app.com/api/v2/ocr/jobs"
$cloudToken = Read-Host "PADDLEOCR_ACCESS_TOKEN (optional)"
$cloudModel = Read-WithDefault "PADDLEOCR_CLOUD_MODEL" "PP-OCRv5"

$lines = @(
    "# Generated by configure-first-run.ps1. Do not commit secrets.",
    "FEISHU_APP_ID=$appId",
    "FEISHU_APP_SECRET=$appSecret",
    "",
    "ORC_OCR_MODE=auto",
    "ORC_OCR_PRIMARY=cloud",
    "ORC_OCR_FALLBACK=local-fast",
    "ORC_TEMPLATE_ID=auto",
    "ORC_CLI_PATH=orc-calc-cli.exe",
    "ORC_CALC_OCR_CACHE_DIR=ocr_cache",
    "",
    "ORC_COMMAND_TIMEOUT=900",
    "ORC_FEISHU_MAX_WORKERS=2",
    "ORC_FEISHU_RUNTIME_DIR=runtime/feishu",
    "ORC_FEISHU_LOG_LEVEL=INFO",
    "ORC_FEISHU_SDK_LOG_LEVEL=WARNING",
    "ORC_FEISHU_REPLY_STYLE=card",
    "ORC_FEISHU_IMAGE_WORKFLOW=auto"
    "",
    "PADDLEOCR_API_URL=$cloudUrl",
    "PADDLEOCR_ACCESS_TOKEN=$($cloudToken.Trim())",
    "PADDLEOCR_CLOUD_MODEL=$cloudModel"
)

Set-Content -LiteralPath $EnvPath -Value $lines -Encoding UTF8

Write-Host ""
Write-Host "Config created. Next, run check-runtime.bat."
